assets: ${RMA_BENCH_ROOT}/libero_fork/libero/assets
bddl_files: ${RMA_BENCH_ROOT}/../bddl
benchmark_root: ${RMA_BENCH_ROOT}/libero_fork/libero
datasets: ${RMA_BENCH_ROOT}/libero_fork/libero/../datasets
init_states: ${RMA_BENCH_ROOT}/libero_fork/libero/init_files
